FROM ghcr.io/astral-sh/uv:alpine

WORKDIR /app

# Copy only dependency metadata first
COPY pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv uv sync

# Copy the rest of the app after deps are installed
COPY . /app

EXPOSE 8080
CMD uv run fastapi run --port 8080
